[package]
name = "iced-chess-experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.6.0", features = ["svg", "canvas"] }
iced_lazy = "0.3.0"
iced_native = "0.7.0"
