[package]
name = "iced-chess-experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.8.0", features = ["svg", "canvas"] }
iced_native = "0.9.1"
pleco = "0.5.0"